mapeamento_disciplinas = {
    'ARTE': 'ARTE',
    'ENS RELIGIOSO': 'ENSINO RELIGIOSO',
    'ENS. RELIGIOSO': 'ENSINO RELIGIOSO',
    'ENS RELIGIOSO.1': 'ENSINO RELIGIOSO',
    'ED FISICA': 'EDUCAÇÃO FÍSICA',
    'ED. FISICA': 'EDUCAÇÃO FÍSICA',
    'PORTUGUÊS': 'LÍNGUA PORTUGUESA',
    'MATEMÁTICA': 'MATEMÁTICA',
    'INGLÊS': 'LÍNGUA INGLESA'
} 